Repository project-leek/project-leek, pull requests merged in 2021-02, with the labels that each got.

#345 343 fix empty group dropdown in edit tag
  packages/app/src/components/edit-tag/EditTag.vue
Labels: bug

#347 346 fix image in addTagStepImage / addTagStepTrack
  packages/app/src/components/add-tag/AddTagStepImage.vue
  packages/app/src/components/add-tag/AddTagStepTrack.vue
  packages/app/src/components/uiBlocks/TagEntry.vue
  packages/commons/src/nfc-tag.class.ts
Labels: bug

#354 Solve connect to box
  .github/workflows/release-app.yml
  docker/app.Dockerfile
  docker/app.Dockerfile.dockerignore
  docker/app/Caddyfile
  packages/app/src/compositions/useBackend.ts
  packages/app/src/router/index.ts
  packages/app/src/views/Setup.vue
Labels: architecture / repo, bug, deployment

#392 change fonts to fit figma
  packages/app/src/App.vue
  packages/app/src/components/uiBlocks/Button.vue
  packages/app/src/components/uiBlocks/Textfield.vue
  packages/app/tailwind.config.js
Labels: UI / app

#362 349 report project management
  docs/report/report.tex
Labels: documentation, report

#316 set a new version of the setup-guide for the pi
  docs/Build.md
Labels: documentation

#478 Fix nfc reader bug
  package.json
  packages/nfc-reader/package.json
  packages/nfc-reader/src/index.ts
Labels: bug

#480 Technologien Vue überarbeitet
  docs/report/literature.bib
  docs/report/report.tex
Labels: report
